### ISSUE TITLE
Error File ine 251   

### ISSUE THREAD

**Issue by jimthedj65** [cslev/pcap_generator#3]
I ran the bash script to create the sample file as a test and when I try to convert it to a pcap I get the following error

File "pcap_generator_from_csv.py", line 251
    print(percent, end="\r")

any ideas, trying on an ubuntu platform?

thanks

**Comment by cslev** [comment]
Of course, I have :)
The problem is that you run it via python2.X instead of python3. Please, use `python3`.
Put differently, test the app like this:
```
python3 pcap_generator_from_csv.py -h
```
If you see the help message, then your issue disappeared.

 I tried to make the code to be python2 and python3 compatible, but some output prettifying parts are very specific. 
And, this line you encountered the error at, is actually some sort of a progress bar for the user.

**Comment by jimthedj65** [comment]
Hi and many thanks for your response that worked a treat, I am sometimes too literal with instructions and thought your example meant it was requiring python 2 doh !

**Comment by cslev** [comment]
Sure, thanks for your comments. Readme was definitely for python2.X. I have just updated to indicate python3 is a MUST :) Thank you

PS: I might rewrite the corresponding code to accept python2 and python3 as well...the main logic does not depend on any of them, just the prettified output.
